#!/bin/bash

set -o pipefail
source /usr/local/bin/process_config.sh


export HORIZON_ENABLED="${HORIZON_ENABLED:-false}"
export REVERB_ENABLED="${REVERB_ENABLED:-false}"

# make sure folder /etc/supervisor.d/ exists
mkdir -p /etc/supervisor.d/

ENABLE_SERVICE=false
if [[ "$HORIZON_ENABLED" == true ]]; then
  printf "Running Horizon ...\n"
  process_config "studs/horizon.ini" "/etc/supervisor.d/horizon.ini"
  ENABLE_SERVICE=true
fi

if [[ "$REVERB_ENABLED" == true ]]; then
  printf "Running Reverb ...\n"
  process_config "studs/reverb.ini" "/etc/supervisor.d/reverb.ini"
  ENABLE_SERVICE=true
fi

if [[ "$ENABLE_SERVICE" == true ]]; then
  supervisord -n -c /etc/supervisord.conf
else
  tail -f /dev/null
fi
