#!/bin/bash

set -o pipefail
source /usr/local/bin/process_config.sh


export HORIZON_ENABLED="${HORIZON_ENABLED:-false}"
export REVERB_ENABLED="${REVERB_ENABLED:-false}"
export SCHEDULE_ENABLED="${SCHEDULE_ENABLED:-false}"
export OCTANE_ENABLED="${OCTANE_ENABLED:-false}"
export OCTANE_WORKERS="${OCTANE_WORKERS:-4}"
export OCTANE_TASK_WORKERS="${OCTANE_TASK_WORKERS:-6}"
export OCTANE_MAX_REQUESTS="${OCTANE_MAX_REQUESTS:-250}"

# make sure folder /etc/supervisor.d/ exists
mkdir -p /etc/supervisor.d/

ENABLE_SERVICE=false
if [[ "$HORIZON_ENABLED" == true ]]; then
  printf "Running Horizon ...\n"
  process_config "studs/horizon.ini" "/etc/supervisor.d/horizon.ini"
  ENABLE_SERVICE=true
fi

if [[ "$REVERB_ENABLED" == true ]]; then
  printf "Running Reverb ...\n"
  process_config "studs/reverb.ini" "/etc/supervisor.d/reverb.ini"
  ENABLE_SERVICE=true
fi

if [[ "$SCHEDULE_ENABLED" == true ]]; then
  printf "Running Schedule ...\n"
  process_config "studs/schedule.ini" "/etc/supervisor.d/schedule.ini"
  ENABLE_SERVICE=true
fi

if [[ "$OCTANE_ENABLED" == true ]]; then
  printf "Running Octane ...\n"
  process_config "studs/octane.ini" "/etc/supervisor.d/octane.ini"
  ENABLE_SERVICE=true
fi

if [[ "$ENABLE_SERVICE" == true ]]; then
  supervisord -n -c /etc/supervisord.conf
else
  tail -f /dev/null
fi
