#!/bin/bash

set -o pipefail
#ARCH_LIST="linux/arm64,linux/amd64,linux/amd64/v2,linux/ppc64le,linux/s390x"
ARCH_LIST="linux/arm64,linux/amd64"

build_image() {
    local OS_IMAGE="$1"
    local DOCKER_FILE="$2"
    local PHP_VERSION="$3"
    if ! docker buildx build --build-arg OS_IMAGE="${OS_IMAGE}" --build-arg PHP_VERSION="${PHP_VERSION}" -f "${DOCKER_FILE}" --platform "$ARCH_LIST" --push -t "humaid/larahost:${PHP_VERSION}" .; then
        printf "Error building base Docker image\n" >&2
        return 1
    fi
}


#build_image "ubuntu:24.04" "Dockerfile" "8.0"
#build_image "ubuntu:24.04" "Dockerfile" "8.1"
#build_image "ubuntu:24.04" "Dockerfile" "8.2"
#build_image "ubuntu:24.04" "Dockerfile" "8.3"
build_image "ubuntu:24.04" "Dockerfile" "8.4"
