#!/bin/bash

set -o pipefail
ARCH_LIST="linux/arm64,linux/amd64,linux/amd64/v2,linux/ppc64le,linux/s390x"

build_image() {
    local OS_IMAGE="$1"
    local DOCKER_FILE="$2"
    local PHP_VERSION="$3"
    local DOCKER_TAG="$4"
    if ! docker buildx build --build-arg OS_IMAGE="${OS_IMAGE}" --build-arg PHP_VERSION="${PHP_VERSION}" -f "${DOCKER_FILE}" --platform "$ARCH_LIST" --push -t "humaid/larahost:${DOCKER_TAG}" .; then
        printf "Error building base Docker image\n" >&2
        return 1
    fi
}


build_image "alpine:3.19" "Dockerfile" "81" "8.1"
build_image "alpine:3.20" "Dockerfile" "82" "8.2"
build_image "alpine:3.20" "Dockerfile" "83" "8.3"
build_image "humaid/larahost:8.1" "Dockerfile-mssql" "81" "8.1-mssql"
build_image "humaid/larahost:8.2" "Dockerfile-mssql" "82" "8.2-mssql"
build_image "humaid/larahost:8.3" "Dockerfile-mssql" "83" "8.3-mssql"
