# Use Alpine as the base image
ARG OS_IMAGE=alpine:3.20
FROM $OS_IMAGE AS builder

LABEL maintainer="Humaid Al Mansoori"

ARG PHP_VERSION=82
ENV ALPINE_FRONTEND=noninteractive \
    PHP_VERSION=$PHP_VERSION \
    PUID=1000 \
    GUID=1000 \
    TZ=UTC

# Install dependencies, bash, Node.js, npm, PHP, and clean up to reduce image size
RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
    build-base autoconf make g++ unixodbc unixodbc-dev curl gnupg && \
    pecl install sqlsrv pdo_sqlsrv && \
    echo "extension=pdo_sqlsrv.so" >> /etc/php$PHP_VERSION/conf.d/10_pdo_sqlsrv.ini && \
    echo "extension=sqlsrv.so" >> /etc/php$PHP_VERSION/conf.d/20_sqlsrv.ini && \
    curl -O https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/msodbcsql18_18.3.3.1-1_arm64.apk && \
    curl -O https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/mssql-tools18_18.3.1.1-1_arm64.apk && \
    curl -O https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/msodbcsql18_18.3.3.1-1_arm64.sig && \
    curl -O https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/mssql-tools18_18.3.1.1-1_arm64.sig && \
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --import - && \
    gpg --verify msodbcsql18_18.3.3.1-1_arm64.sig msodbcsql18_18.3.3.1-1_arm64.apk && \
    gpg --verify mssql-tools18_18.3.1.1-1_arm64.sig mssql-tools18_18.3.1.1-1_arm64.apk && \
    apk add --allow-untrusted msodbcsql18_18.3.3.1-1_arm64.apk mssql-tools18_18.3.1.1-1_arm64.apk && \
    rm -rf /var/cache/apk/* /tmp/* /var/tmp/* /usr/share/man /usr/share/doc /usr/share/info /usr/share/licenses /root/.gnupg && \
    find / -type f -name "*.apk-new" -exec rm {} +

# Start from a clean state
FROM $OS_IMAGE

# Copy files from builder stage
COPY --from=builder / /

# Set environment variables
ENV TZ=UTC \
    PUID=1000 \
    GUID=1000

# Set working directory
WORKDIR /home/docker/www

# Expose the necessary port
EXPOSE 80

# Define the entrypoint
ENTRYPOINT ["start-container"]
