#!/bin/bash

set -o pipefail
source /usr/local/bin/process_config.sh

# make sure dir /etc/nginx/http.default.d exists
mkdir -p /etc/nginx/http.default.d

export DOLLAR="$"
export UPLOAD_LIMIT="${UPLOAD_LIMIT:-2M}"
export PUBLIC_ROOT="${PUBLIC_ROOT:-/home/docker/www/public}"
export PHP_FPM_ENABLED="${PHP_FPM_ENABLED:-true}"
export REVERB_ENABLED="${REVERB_ENABLED:-false}"
export OCTANE_ENABLED="${OCTANE_ENABLED:-false}"
export MAIL_ENABLED="${MAIL_ENABLED:-false}"
export MAIL_ADDRESS="${MAIL_ADDRESS:-false}"
export MAIL_WEBROOT="${MAIL_WEBROOT:-/larahost/mail/}"
export PMA_ENABLED="${PMA_ENABLED:-false}"
export PMA_ADDRESS="${PMA_ADDRESS:-false}"
export PMA_WEBROOT="${PMA_WEBROOT:-/larahost/pma/}"
export PMA_UPLOAD_LIMIT="${PMA_UPLOAD_LIMIT:-10m}"
export PMA_MAX_EXECUTION_TIME="${PMA_MAX_EXECUTION_TIME:-600}"


process_config "studs/nginx.conf" "/etc/nginx/nginx.conf"
if [[ "$OCTANE_ENABLED" == true ]]; then
  printf "Running nginx (Octane) ...\n"
  process_config "studs/octane.conf" "/etc/nginx/http.d/default.conf"
else
  printf "Running nginx (PHP-FPM) ...\n"
  process_config "studs/fpm.conf" "/etc/nginx/http.d/default.conf"
fi

if [[ "$REVERB_ENABLED" == true ]]; then
  process_config "studs/reverb.conf" "/etc/nginx/http.default.d/reverb.conf"
fi

if [[ "$MAIL_ENABLED" == true ]]; then
  process_config "studs/mail.conf" "/etc/nginx/http.default.d/mail.conf"
fi

if [[ "$PMA_ENABLED" == true ]]; then
  process_config "studs/pma.conf" "/etc/nginx/http.default.d/pma.conf"
fi

exec nginx -g "daemon off;"


#if [[ "$OCTANE_ENABLED" == false ]]; then
#  if [[ "$PHP_FPM_ENABLED" == true ]]; then
#    process_config "studs/fpm.conf" "/etc/nginx/http.d/default.conf"
#  else
#    process_config "studs/default.conf" "/etc/nginx/http.d/default.conf"
#  fi
#
#else
#  tail -f /dev/null
#fi
#
