#!/bin/bash

set -o pipefail

printf "Running supervisor ...\n"

main() {
    local tmp_file; tmp_file=$(mktemp)

    process_supervisor_conf "$tmp_file"
    move_file "$tmp_file" "/etc/supervisor/supervisord.conf"

    if [[ "$QUEUE_ENABLED" == true ]]; then
        printf "%s\n" "$QUEUE_NAMES"
        process_queue_names
    fi

    supervisord -n -c /etc/supervisor/supervisord.conf
}

process_supervisor_conf() {
    local tmp_file="$1"
    if ! envsubst < studs/supervisord.conf | tee "$tmp_file" > /dev/null; then
        printf "Error processing supervisor config\n" >&2
        return 1
    fi
}

move_file() {
    local src="$1"
    local dest="$2"
    if ! mv "$src" "$dest"; then
        printf "Error moving file from %s to %s\n" "$src" "$dest" >&2
        return 1
    fi
}

process_queue_names() {
    local tmp_file; tmp_file=$(mktemp)
    local IFS="," names="$QUEUE_NAMES"

    for w in $names; do
        local tmp_lv_name="${w%:*}"
        local tmp_lv_workers="${w#*:}"
        local tmp_lv_logs="/dev/fd/1"

        [[ "$QUEUE_ENABLE_LOG" == true ]] && tmp_lv_logs="/www/storage/logs/$tmp_lv_name-worker.log"

        export TMP_LV_NAME="$tmp_lv_name"
        export TMP_LV_WORKERS="$tmp_lv_workers"
        export TMP_LV_LOGS="$tmp_lv_logs"

        if ! envsubst < studs/laravel-worker.conf | tee "$tmp_file" > /dev/null; then
            printf "Error processing laravel worker config for %s\n" "$tmp_lv_name" >&2
            return 1
        fi

        move_file "$tmp_file" "/etc/supervisor/conf.d/$tmp_lv_name-workers.conf"

        unset TMP_LV_NAME TMP_LV_WORKERS TMP_LV_LOGS
    done
}

main
