#!/bin/bash

set -o pipefail

printf "Running supervisor ...\n"

main() {
    local tmp_file; tmp_file=$(mktemp)

    process_supervisor_conf "$tmp_file"
    move_file "$tmp_file" "/etc/supervisor/supervisord.conf"

    supervisord -n -c /etc/supervisor/supervisord.conf
}

process_supervisor_conf() {
    local tmp_file="$1"
    # shellcheck disable=SC2002
    if ! cat studs/supervisord.conf | envsubst "$(env | cut -d= -f1 | sed -e 's/^/$/')" | tee "$tmp_file" > /dev/null; then
        printf "Error processing supervisor config\n" >&2
        return 1
    fi
}

move_file() {
    local src="$1"
    local dest="$2"
    if ! mv "$src" "$dest"; then
        printf "Error moving file from %s to %s\n" "$src" "$dest" >&2
        return 1
    fi
}

main
