#!/bin/bash

echo "Running supervisor ..."

tmpFile=$(mktemp)
cat studs/supervisord.conf | envsubst "$(env | cut -d= -f1 | sed -e 's/^/$/')" | tee "$tmpFile" > /dev/null
mv "$tmpFile" /etc/supervisor/supervisord.conf
if [ "$QUEUE_ENABLED" = true ] ; then
  echo $QUEUE_NAMES;
  for w in $(echo "$QUEUE_NAMES" | tr "," " ") ; do
    export TMP_LV_NAME=${w%:*}
    export TMP_LV_WORKERS=${w#*:}
    export TMP_LV_LOGS=/dev/fd/1
    if [ "$QUEUE_ENABLE_LOG" = true ] ; then
      export TMP_LV_LOGS=/home/docker/www/storage/logs/$TMP_LV_NAME-worker.log
    fi
    cat studs/laravel-worker.conf | envsubst "$(env | cut -d= -f1 | sed -e 's/^/$/')" | tee "$tmpFile" > /dev/null
    mv "$tmpFile" /etc/supervisor/conf.d/$TMP_LV_NAME-workers.conf
    unset TMP_LV_NAME
    unset TMP_LV_WORKERS
    unset TMP_LV_LOGS
  done;
fi

supervisord -n -c /etc/supervisor/supervisord.conf
