#!/bin/bash

set -o pipefail

source /usr/local/bin/process_config.sh
php_version=$(basename "$(/usr/bin/php -r 'echo PHP_BINARY;')" | grep -o 'php[0-9]\+')
# Maximum time in seconds a script is allowed to parse input data, like POST and GET.
export PHP_MAX_INPUT_TIME="${PHP_MAX_INPUT_TIME:60}"
# Whether to allow the treatment of URLs (like http:// or ftp://) as files.
export PHP_ALLOW_URL_FOPEN="${PHP_ALLOW_URL_FOPEN:-on}"
# Determines whether errors should be printed to the screen as part of the output.
export PHP_DISPLAY_ERRORS="${PHP_DISPLAY_ERRORS:-off}"
# Whether to allow HTTP file uploads.
export PHP_FILE_UPLOADS="${PHP_FILE_UPLOADS:-on}"
# Maximum execution time of each script, in seconds.
export PHP_MAX_EXECUTION_TIME="${PHP_MAX_EXECUTION_TIME:-30}"
# How many input variables may be accepted (limit for GET, POST, and COOKIE input).
export PHP_MAX_INPUT_VARS="${PHP_MAX_INPUT_VARS:-1000}"
# Maximum amount of memory a script may consume.
export PHP_MEMORY_LIMIT="${PHP_MEMORY_LIMIT:-128M}"
# Whether to transparently compress output using the zlib library.
export PHP_ZLIB_OUTPUT_COMPRESSION="${PHP_ZLIB_OUTPUT_COMPRESSION:-off}"
#
export PHP_FPM_ENABLED="${PHP_FPM_ENABLED:-true}"
export UPLOAD_LIMIT="${UPLOAD_LIMIT:-2M}"

if [[ "$PHP_FPM_ENABLED" == true ]]; then
    printf "Running PHP-FPM ...\n"
    process_config "studs/php.ini" "/etc/$php_version/php.ini"
    process_config "studs/custom.ini" "/etc/$php_version/conf.d/custom.ini"
    process_config "studs/www.conf" "/etc/$php_version/php-fpm.d/www.conf"
    chmod 644 "studs/php.ini" "/etc/$php_version/php.ini"
    chmod 644 "/etc/$php_version/conf.d/custom.ini"
    chmod 644 "/etc/$php_version/php-fpm.d/www.conf"
    /usr/bin/php-fpm -F
else
  tail -f /dev/null
fi
