#!/bin/bash

tmpFile=$(mktemp)
cat studs/custom.ini | envsubst "$(env | cut -d= -f1 | sed -e 's/^/$/')" | tee "$tmpFile" > /dev/null
mv "$tmpFile" /etc/php/$PHP_VERSION/fpm/conf.d/custom.ini
if [ "$PHP_FPM_ENABLED" == true ] ; then
  echo "Running php-fpm ..."
  echo 'PHP-FPM: On!'
  cat studs/www.conf | envsubst "$(env | cut -d= -f1 | sed -e 's/^/$/')" | tee "$tmpFile" > /dev/null
  mv "$tmpFile" /etc/php/$PHP_VERSION/fpm/pool.d/www.conf
  /usr/sbin/php-fpm$PHP_VERSION
fi
tail -f
