#!/bin/ash

tmpFile=$(mktemp)
cat studs/custom.ini | envsubst "$(env | cut -d= -f1 | sed -e 's/^/$/')" | tee "$tmpFile" > /dev/null
mv "$tmpFile" /etc/php$PHP_VERSION/conf.d/custom.ini
if [ "$LARAHOST_OCTANE_ENABLED" != true ] ; then
  echo "Running php-fpm ..."
  echo 'PHP-FPM: On!'
#  cat studs/php-fpm.conf | envsubst "$(env | cut -d= -f1 | sed -e 's/^/$/')" | tee "$tmpFile" > /dev/null
#  mv "$tmpFile" /usr/local/etc/php-fpm.conf
  cat studs/www.conf | envsubst "$(env | cut -d= -f1 | sed -e 's/^/$/')" | tee "$tmpFile" > /dev/null
  mv "$tmpFile" /etc/php$PHP_VERSION/php-fpm.d/www.conf
  exec php-fpm$PHP_VERSION --nodaemonize
fi
tail -f
